import React from 'react';

export interface FmiFactorsPanelProps {
  insights: string[];
  factors: string[];
}

export const FmiFactorsPanel: React.FC<FmiFactorsPanelProps> = ({
  insights,
  factors,
}) => {
  return (
    <div className="insights-card">
      {/* 1. Why is my FMI this score? (Backend insights) */}
      <div className="card-header-row">
        <div>
          <h3 className="card-title">Why Your FMI Looks Like This</h3>
          <p className="card-subtitle">
            Deterministic explanations generated by the FMI scoring engine
          </p>
        </div>
      </div>

      {insights.length === 0 ? (
        <p className="text-secondary text-sm" style={{ marginTop: '12px' }}>
          Record daily financial activity to generate tailored score insights.
        </p>
      ) : (
        <div className="fmi-insights-list">
          {insights.slice(0, 5).map((insight, idx) => (
            <div key={idx} className="fmi-insight-item">
              <span className="insight-bullet">▸</span>
              <span className="insight-text text-sm">{insight}</span>
            </div>
          ))}
        </div>
      )}

      {/* 2. Factors affecting your FMI (Neutral display per Correction #2) */}
      {factors.length > 0 && (
        <div className="fmi-factors-subpanel">
          <h4 className="fmi-subpanel-title text-xs font-semibold text-tertiary">
            Factors Affecting Your FMI
          </h4>
          <div className="factors-neutral-list">
            {factors.map((factor, idx) => (
              <div key={idx} className="factor-neutral-chip">
                <span className="factor-dot" />
                <span className="factor-text text-xs text-secondary">{factor}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
