import React from 'react';

export interface FmiFactorsPanelProps {
  insights: string[];
  factors: string[];
}

export const FmiFactorsPanel: React.FC<FmiFactorsPanelProps> = ({
  insights,
  factors,
}) => {
  return (
    <div className="insights-card">
      <div className="card-header-row">
        <div>
          <span className="overview-context-badge">DIAGNOSTIC FACTORS</span>
          <h3 className="card-title">Factors affecting your FMI</h3>
          <p className="card-subtitle">
            Deterministic explanations generated by the FMI scoring engine
          </p>
        </div>
      </div>

      {insights.length === 0 ? (
        <p className="text-secondary text-sm" style={{ marginTop: '12px' }}>
          Record daily financial activity to generate tailored score insights.
        </p>
      ) : (
        <div className="fmi-insights-list">
          {insights.slice(0, 5).map((insight, idx) => (
            <div key={idx} className="fmi-insight-item">
              <span className="insight-bullet" aria-hidden="true">▸</span>
              <span className="insight-text text-sm text-secondary">{insight}</span>
            </div>
          ))}
        </div>
      )}

      {factors.length > 0 && (
        <div className="fmi-factors-subpanel">
          <h4 className="fmi-subpanel-title text-xs font-semibold text-tertiary uppercase tracking-wider">
            Active Factor Drivers
          </h4>
          <div className="factors-neutral-list">
            {factors.map((factor, idx) => (
              <div key={idx} className="factor-neutral-chip">
                <span className="factor-dot" aria-hidden="true" />
                <span className="factor-text text-xs text-secondary">{factor}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
